Ebene\MvpBundle\Entity\Abonnement:
    type: entity
    table: abonnement
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        nombretag:
            type: int
        prixtotal:
            type: float
        facture:
            type: string
            length: 255
        datedeb:
            type: datetime
        datefin:
            type: datetime
    manyToOne:
        restaurant:
            targetEntity: Retaurant
            inversedBy: listeabonnements
            joinColumn:
                name: restaurant_id
                referencedColumnName: id