Ebene\MvpBundle\Entity\Article:
    type: entity
    table: article
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        nom:
            type: string
            length: 255
        description:
            type: text
            nullable: true
        prix:
            type: float
        photo:
            type: string
            length: 255
            nullable: true
    manyToOne:
        commande:
            targetEntity: Commande
            inversedBy: listearticles
            joinColumn:
                name: commande_id
                referencedColumnName: id
        section:
            targetEntity: Section
            inversedBy: listearticles
            joinColumn:
                name: section_id
                referencedColumnName: id
    manyToMany:
        listesecondaires:
            targetEntity: Secondaire
            inversedBy: listearticles
            joinTable:
                name: articles_secondaires
                joinColumns:
                    articles_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    secondaires_id:
                        referencedColumnName: id