Ebene\MvpBundle\Entity\Restaurant:
    type: entity
    table: restaurant
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        nom:
            type: string
            length: 255
        couleur1:
            type: string
            length: 255
        couleur2:
            type: string
            length: 255
        couleur3:
            type: string
            length: 255
        dateexp:
            type: datetime
            nullable: true
    manyToOne:
        proprietaire:
            targetEntity: Proprietaire
            inversedBy: restaurants
            joinColumn:
                name: proprietaire_id
                referencedColumnName: id
    oneToMany:
        commandes:
            targetEntity: Commande
            mappedBy: restaurant
        sections:
            targetEntity: Section
            mappedBy: restaurant
        employes:
            targetEntity: Employe
            mappedBy: restaurant
        abonnements:
            targetEntity: Abonnement
            mappedBy: restaurant