mvp_abonnement:
    path:     /
    defaults: { _controller: "EbeneMvpBundle:Abonnement:index" }

mvp_abonnement_show:
    path:     /{id}/show
    defaults: { _controller: "EbeneMvpBundle:Abonnement:show" }

mvp_abonnement_new:
    path:     /new
    defaults: { _controller: "EbeneMvpBundle:Abonnement:new" }

mvp_abonnement_create:
    path:     /create
    defaults: { _controller: "EbeneMvpBundle:Abonnement:create" }
    requirements: { _method: post }

mvp_abonnement_edit:
    path:     /{id}/edit
    defaults: { _controller: "EbeneMvpBundle:Abonnement:edit" }

mvp_abonnement_update:
    path:     /{id}/update
    defaults: { _controller: "EbeneMvpBundle:Abonnement:update" }
    requirements: { _method: post|put }

mvp_abonnement_delete:
    path:     /{id}/delete
    defaults: { _controller: "EbeneMvpBundle:Abonnement:delete" }
    requirements: { _method: post|delete }
