mvp_article:
    path:     /
    defaults: { _controller: "EbeneMvpBundle:Article:index" }

mvp_article_show:
    path:     /{id}/show
    defaults: { _controller: "EbeneMvpBundle:Article:show" }

mvp_article_new:
    path:     /new
    defaults: { _controller: "EbeneMvpBundle:Article:new" }

mvp_article_create:
    path:     /create
    defaults: { _controller: "EbeneMvpBundle:Article:create" }
    requirements: { _method: post }

mvp_article_edit:
    path:     /{id}/edit
    defaults: { _controller: "EbeneMvpBundle:Article:edit" }

mvp_article_update:
    path:     /{id}/update
    defaults: { _controller: "EbeneMvpBundle:Article:update" }
    requirements: { _method: post|put }

mvp_article_delete:
    path:     /{id}/delete
    defaults: { _controller: "EbeneMvpBundle:Article:delete" }
    requirements: { _method: post|delete }
