Ebene_commande:
    path:     /
    defaults: { _controller: "EbeneMvpBundle:Commande:index" }

Ebene_commande_show:
    path:     /{id}/show
    defaults: { _controller: "EbeneMvpBundle:Commande:show" }

Ebene_commande_new:
    path:     /new
    defaults: { _controller: "EbeneMvpBundle:Commande:new" }

Ebene_commande_create:
    path:     /create
    defaults: { _controller: "EbeneMvpBundle:Commande:create" }
    requirements: { _method: post }

Ebene_commande_edit:
    path:     /{id}/edit
    defaults: { _controller: "EbeneMvpBundle:Commande:edit" }

Ebene_commande_update:
    path:     /{id}/update
    defaults: { _controller: "EbeneMvpBundle:Commande:update" }
    requirements: { _method: post|put }

Ebene_commande_delete:
    path:     /{id}/delete
    defaults: { _controller: "EbeneMvpBundle:Commande:delete" }
    requirements: { _method: post|delete }
