mvp_employe:
    path:     /
    defaults: { _controller: "EbeneMvpBundle:Employe:index" }

mvp_employe_show:
    path:     /{id}/show
    defaults: { _controller: "EbeneMvpBundle:Employe:show" }

mvp_employe_new:
    path:     /new
    defaults: { _controller: "EbeneMvpBundle:Employe:new" }

mvp_employe_create:
    path:     /create
    defaults: { _controller: "EbeneMvpBundle:Employe:create" }
    requirements: { _method: post }

mvp_employe_edit:
    path:     /{id}/edit
    defaults: { _controller: "EbeneMvpBundle:Employe:edit" }

mvp_employe_update:
    path:     /{id}/update
    defaults: { _controller: "EbeneMvpBundle:Employe:update" }
    requirements: { _method: post|put }

mvp_employe_delete:
    path:     /{id}/delete
    defaults: { _controller: "EbeneMvpBundle:Employe:delete" }
    requirements: { _method: post|delete }
